# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

notifications:
  email: false

sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4.0.0'
  - '4.1.2'
  - '4.2.2'
  - '5.0.0'
  - '5.1.0'

before_script:
  - 'npm install -g gulp'

before_install:
  - 'npm i'

install:
  - 'npm test'

after_success:
  - 'npm run-script coverage'

deploy:
  provider: npm
  email: info@invenio-software.org
  api_key:
    secure: mVjw6DB1kmDXjaJy5KfL6ztRHll0WTecU2DuJyVadx6E00snROlx9TDE+OkIKNbh4aJBfok2JvtiVzh5J11X2hQ0mJs/oKkv49Tbqf44CGpmm1sRSYdnGQZpkqSLvLeMi/R2V81vrC3Cf9+08wJCRagQR5Pm0/h9vmP8DJFwoD1JfB7K8coo8KO1M9npNxA/d6jYe1Z6seT7bKVrnRVlJZFpPRPwoYg1cO7j1ZZ1ovpkqYLHSpHAC8RdJBplx6/gBtdcfvUAb+0vlKkRD47beuydzPPSy7x3iK9sr6+8RpAKNL5m7avCh0sYy/VG0G0YIvCwAshA+PHHrifBWuamgQdadKtStSL3rc/DvNm+q2q6EUk1ACWA9o0SVPqMKjjLoyv9eHUbUV6amZWU4LrEZ3tZb2C0QCYbAbh5rLEn107cFTqQ+S45nui8XBWFTo0H7tfgKiNZ/mSVyhgLTYDdr8xXak3kvnXzCjHop/nSIFx+dnmiw9YHq6QQ58l//MYS90zHjSGBZASKyGb6h1P+5ZILcNdGYNTXp98faC0DXrcJgVcq8qLcHhyPkrG0segiA1o4y/u4R4tmJFrifjPwNt/KTWe9411gI6NxWatDB4AZkD2CdXEUScWGy6g7AcMXJJDYHDhEu+lsUEjzDeUwZQ4W4YawzGOwpJwJihU1Y70=
  on:
    tags: true
    repo: inveniosoftware/invenio-search-js
    branch: master
